INSERT INTO equipes_equipe VALUES(1, 'Atlético - MG', 'CAM', 'emblemas/atletico-mg.png');
INSERT INTO equipes_equipe VALUES(2, 'Atlético - PR', 'CAP', 'emblemas/atletico-pr.png');
INSERT INTO equipes_equipe VALUES(3, 'Bahia', 'BAI', 'emblemas/bahia.png');
INSERT INTO equipes_equipe VALUES(4, 'Botafogo', 'BOT', 'emblemas/botafogo.png');
INSERT INTO equipes_equipe VALUES(5, 'Chapecoense', 'CHA', 'emblemas/chapecoense.png');
INSERT INTO equipes_equipe VALUES(6, 'Corinthians', 'COR', 'emblemas/corinthians.png');
INSERT INTO equipes_equipe VALUES(7, 'Coritiba', 'CTB', 'emblemas/coritiba.png');
INSERT INTO equipes_equipe VALUES(8, 'Criciuma', 'CRI', 'emblemas/criciuma.png');
INSERT INTO equipes_equipe VALUES(9, 'Cruzeiro', 'CRU', 'emblemas/cruzeiro.png');
INSERT INTO equipes_equipe VALUES(10, 'Figueirense', 'FIG', 'emblemas/figueirense.png');
INSERT INTO equipes_equipe VALUES(11, 'Flamengo', 'FLA', 'emblemas/flamengo.png');
INSERT INTO equipes_equipe VALUES(12, 'Fluminense', 'FLU', 'emblemas/fluminense.png');
INSERT INTO equipes_equipe VALUES(13, 'Goiás', 'GOI', 'emblemas/goias.png');
INSERT INTO equipes_equipe VALUES(14, 'Grêmio', 'GRE', 'emblemas/gremio.png');
INSERT INTO equipes_equipe VALUES(15, 'Internacional', 'INT', 'emblemas/internacional.png');
INSERT INTO equipes_equipe VALUES(16, 'Palmeiras', 'PAL', 'emblemas/palmeiras.png');
INSERT INTO equipes_equipe VALUES(17, 'Santos', 'SAN', 'emblemas/santos.png');
INSERT INTO equipes_equipe VALUES(18, 'São Paulo', 'SAO', 'emblemas/sao-paulo.png');
INSERT INTO equipes_equipe VALUES(19, 'Sport', 'SPO', 'emblemas/sport.png');
INSERT INTO equipes_equipe VALUES(20, 'Vitória', 'VIT', 'emblemas/vitoria.png');
