INSERT INTO equipes_equipe VALUES(1, 'Atlético - MG', 'CAM', 'atletico-mg.png');
INSERT INTO equipes_equipe VALUES(2, 'Atlético - PR', 'CAP', 'atletico-pr.png');
INSERT INTO equipes_equipe VALUES(3, 'Bahia', 'BAI', 'bahia.png');
INSERT INTO equipes_equipe VALUES(4, 'Botafogo', 'BOT', 'botafogo.png');
INSERT INTO equipes_equipe VALUES(5, 'Chapecoense', 'CHA', 'chapecoense.png');
INSERT INTO equipes_equipe VALUES(6, 'Corinthians', 'COR', 'corinthians.png');
INSERT INTO equipes_equipe VALUES(7, 'Coritiba', 'CTB', 'coritiba.png');
INSERT INTO equipes_equipe VALUES(8, 'Criciuma', 'CRI', 'criciuma.png');
INSERT INTO equipes_equipe VALUES(9, 'Cruzeiro', 'CRU', 'cruzeiro.png');
INSERT INTO equipes_equipe VALUES(10, 'Figueirense', 'FIG', 'figueirense.png');
INSERT INTO equipes_equipe VALUES(11, 'Flamengo', 'FLA', 'flamengo.png');
INSERT INTO equipes_equipe VALUES(12, 'Fluminense', 'FLU', 'fluminense.png');
INSERT INTO equipes_equipe VALUES(13, 'Goiás', 'GOI', 'goias.png');
INSERT INTO equipes_equipe VALUES(14, 'Grêmio', 'GRE', 'gremio.png');
INSERT INTO equipes_equipe VALUES(15, 'Internacional', 'INT', 'internacional.png');
INSERT INTO equipes_equipe VALUES(16, 'Palmeiras', 'PAL', 'palmeiras.png');
INSERT INTO equipes_equipe VALUES(17, 'Santos', 'SAN', 'santos.png');
INSERT INTO equipes_equipe VALUES(18, 'São Paulo', 'SAO', 'sao-paulo.png');
INSERT INTO equipes_equipe VALUES(19, 'Sport', 'SPO', 'sport.png');
INSERT INTO equipes_equipe VALUES(20, 'Vitória', 'VIT', 'vitoria.png');
